object Versions {

    const val pagingLibKtx: String = "2.1.0"
    const val roomCoreVersion: String = "2.2.0-rc01"
    const val roomLibCompiler: String = "2.2.0-rc01"
    const val roomVersion: String = "2.2.0-rc01"
    const val coreAnko: String = "0.10.8"
    const val okhttpVersion: String = "4.0.0"
    const val mouchine: String = "2.6.1"
    const val coroutineVersion: String = "1.3.0"
    const val pagingLibCompiler: String = "2.1.0"
    const val cardViewVersion: String = "1.0.0"
    const val glideCompiler: String = "4.9.0"
    const val glideVersion: String = "4.9.0"
    const val testRunner: String = "1.2.0"
    const val pagingLib: String = "2.1.0"
    const val LifecycleCompile: String = "2.0.0"
    const val liveDataKtx: String = "2.2.0-alpha03"
    const val legacySupport: String = "1.0.0"
    const val kotlinLib = "1.3.71"
    const val minSDK = 23
    const val targetSDK = 29
    const val compileSDK = 29
    const val retrofit = "2.5.0"
    const val gson = "2.8.5"
    const val gsonConverter = "2.5.0"
    const val httpLogging = "3.12.0"
    const val koin = "2.0.1"
    const val koinArch = "0.9.1"
    const val rxKotlin = "2.2.0"
    const val leakCanary = "1.6.3"
    const val junit = "4.12"
    const val aws = "2.11.1"
    const val mockito = "2.8.47"
    const val rxAndroid = "2.1.1"
    const val rxAndroidTest = "3.2.0"
    const val rxJava = retrofit
    const val appCompat = "1.0.2"
    const val coreKtx: String = "1.0.2"
    const val materialComponents = "1.0.0"
    const val archComp = "2.0.0"
    const val archExt = "2.0.0"
    const val constraintLayout = "1.1.3"
    const val jodaTime = "2.10.1"
    const val navigationGraph = "2.1.0-alpha02"
    const val reactiveNetwork = "3.0.3"
    const val workManager = "2.1.0-rc01"
    const val powerMokito = "1.7.0RC4"
    const val places = "2.0.0"
    const val biometic = "1.0.0-beta02"
    const val recyclerview = "1.1.0"
    const val recyclerviewSelection = "1.1.0-beta01"
    const val picasso = "2.71828"
    const val mockk = "1.9.3"
    const val archCoreTesting = "2.1.0"
    const val navigationSafeArgs = "2.2.0-alpha03"
    const val viewModelKtx = "2.0.0"
}

object LibDeps {

    const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlinLib}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val picasso = "com.squareup.picasso:picasso:${Versions.picasso}"
    const val gson = "com.google.code.gson:gson:${Versions.gson}"
    const val gsonConverter = "com.squareup.retrofit2:converter-gson:${Versions.gsonConverter}"
    const val okHttp3 = "com.squareup.okhttp3:okhttp:${Versions.okhttpVersion}"
    const val httpLogging = "com.squareup.okhttp3:logging-interceptor:${Versions.httpLogging}"
    const val koinCore = "org.koin:koin-core:${Versions.koin}"
    const val koin = "org.koin:koin-android:${Versions.koin}"
    const val koinScope = "org.koin:koin-androidx-scope:${Versions.koin}"
    const val rxKotlin = "io.reactivex.rxjava2:rxkotlin:${Versions.rxKotlin}"
    const val junit = "junit:junit:${Versions.junit}"
    const val aws = "com.amazonaws:aws-android-sdk-mobile-client:${Versions.aws}"
    const val awsUserPool = "com.amazonaws:aws-android-sdk-auth-userpools:${Versions.aws}"
    const val mockito = "org.mockito:mockito-core:${Versions.mockito}"
    const val mockitoAndroid = "org.mockito:mockito-android:${Versions.mockito}"
    const val rxAndroid = "io.reactivex.rxjava2:rxandroid:${Versions.rxAndroid}"
    const val androidxTest = "androidx.test.espresso:espresso-core:${Versions.rxAndroidTest}"
    const val koinTest = "org.koin:koin-test:${Versions.koin}"
    const val rxJavaAdapter = "com.squareup.retrofit2:adapter-rxjava2:${Versions.rxJava}"
    const val appCompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    const val materialComponents =
        "com.google.android.material:material:${Versions.materialComponents}"
    const val lifecycleRuntime = "androidx.lifecycle:lifecycle-runtime:${Versions.archComp}"
    const val lifeCycleExtn = "androidx.lifecycle:lifecycle-extensions:${Versions.archExt}"
    const val lifeCycleCommon = "androidx.lifecycle:lifecycle-common:${Versions.archComp}"
    const val jodaTime = "joda-time:joda-time:${Versions.jodaTime}"
    const val reactiveNetwork =
        "com.github.pwittchen:reactivenetwork-rx2:${Versions.reactiveNetwork}"
    const val workManager = "androidx.work:work-runtime-ktx:${Versions.workManager}"
    const val powerMockitoCore = "org.powermock:powermock-core:${Versions.powerMokito}"
    const val powerMockitoModule = "org.powermock:powermock-module-junit4:${Versions.powerMokito}"
    const val powerMockMokito = "org.powermock:powermock-api-mockito2:${Versions.powerMokito}"
    const val mockk = "io.mockk:mockk:${Versions.mockk}"
    const val archCoreTesting = "androidx.arch.core:core-testing:${Versions.archCoreTesting}"
    const val appCoreKTX = "androidx.core:core-ktx:${Versions.coreKtx}"
    const val legacySupport = "androidx.legacy:legacy-support-v4:${Versions.legacySupport}"
    const val lifecycleViewmodelKtx =
        "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.viewModelKtx}"
    const val lifeCycleLiveDataKtx =
        "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.liveDataKtx}"
    const val pagingLib = "androidx.paging:paging-runtime:${Versions.pagingLib}"
    const val testRunner = "androidx.test:runner:${Versions.testRunner}"
    const val glideLib = "com.github.bumptech.glide:glide:${Versions.glideVersion}"
    const val glideCompiler = "com.github.bumptech.glide:compiler:${Versions.glideCompiler}"
    const val pagingLibCompiler = "androidx.paging:paging-runtime:${Versions.pagingLibCompiler}"
    const val coroutineLib =
        "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutineVersion}"
    const val mouchine = "com.squareup.retrofit2:converter-moshi:${Versions.mouchine}"
    const val coreAnko = "org.jetbrains.anko:anko:${Versions.coreAnko}"
    const val roomLib = "androidx.room:room-runtime:${Versions.roomVersion}"
    const val roomLibCompiler = "androidx.room:room-compiler:${Versions.roomLibCompiler}"
    const val roomCore = "androidx.room:room-ktx:${Versions.roomCoreVersion}"
    const val pagingLibKtx = "androidx.paging:paging-runtime-ktx:${Versions.pagingLibKtx}"
}

object AppDeps {

    const val koinAndroidArch = "org.koin:koin-android-architecture:${Versions.koinArch}"
    const val koinViewModel = "org.koin:koin-androidx-viewmodel:${Versions.koin}"
    const val appCompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    const val materialComponents =
        "com.google.android.material:material:${Versions.materialComponents}"
    const val constraintLayout =
        "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    const val navigationFragment =
        "androidx.navigation:navigation-fragment-ktx:${Versions.navigationGraph}"
    const val navigationUi = "androidx.navigation:navigation-ui-ktx:${Versions.navigationGraph}"
    const val places = "com.google.android.libraries.places:places:${Versions.places}"
    const val biometric = "androidx.biometric:biometric:${Versions.biometic}"
    const val recyclerView = "androidx.recyclerview:recyclerview:${Versions.recyclerview}"
    const val recyclerViewSelection =
        "androidx.recyclerview:recyclerview-selection:${Versions.recyclerviewSelection}"
    const val lifeCycleCompiler =
        "androidx.lifecycle:lifecycle-compiler:${Versions.LifecycleCompile}"
    const val cardViewVersion = "androidx.cardview:cardview:${Versions.cardViewVersion}"
}